= Print service lookup a virtual printers
Patrick Reinhart <https://github.com/reinhapa[@reinhapa]>
:group-name: net.reini
:project-org: reinhapa
:project-name: virtual-printer
:project-full-path: {project-org}/{project-name}
:github-branch: master

image:https://img.shields.io/badge/license-MIT-blue.svg["MIT License", link="https://github.com/{project-full-path}/blob/{github-branch}/LICENSE"]
image:https://img.shields.io/badge/Java-11-blue.svg["Java 11", link="https://adoptium.net"]
image:https://img.shields.io/badge/Java-17-blue.svg["Java 17", link="https://adoptium.net"]
image:https://img.shields.io/badge/Java-21-blue.svg["Java 21", link="https://adoptium.net"]
image:https://img.shields.io/github/release/{project-full-path}.svg["Release", link="https://github.com/{project-full-path}/releases"]
image:https://img.shields.io/maven-central/v/{group-name}/{project-name}.svg?label=Maven%20Central["Maven Central", link="https://search.maven.org/search?q=g:%22{group-name}%22%20AND%20a:%22{project-name}%22"]
image:https://sonarcloud.io/api/project_badges/measure?project={project-org}_{project-name}&metric=alert_status["Quality Gate Status", link ="https://sonarcloud.io/summary/new_code?id={project-org}_{project-name}"]
image:https://javadoc.io/badge2/{group-name}/{project-name}/javadoc.svg["javadoc", link="https://javadoc.io/doc/{group-name}/{project-name}"]
image:https://github.com/{project-full-path}/actions/workflows/gradle.yml/badge.svg["CI", link="https://github.com/{project-full-path}/actions/workflows/gradle.yml"]

== Usage
In order to use the virtual printer you simply have to put the library on your class path.
From this point on you will find a least one printer `VirtualPrinter` and therefore a default printer even you
do not have any actual printer installed.

In the case where printers have been installed you find an additional `VirtualPrinter` as one along them.

In case of a `virtual-printer-names` resources exists on the class path, all non empty lines after trimming
all leading and tailing whitespace characters will used to create virtual printer names in the order of their 
location on the class path. Duplicate names will be skipped.

== Contribute
Contributions are always welcome. Use https://google.github.io/styleguide/javaguide.html[Google code style format] for your changes. 

== License
This project is licensed under the https://github.com/{project-full-path}/blob/{github-branch}/LICENSE[MIT license]