# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }} / OpenJDK ${{ matrix.jdk }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: ['11', '17', '18']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: SonarQube
      if:  ${{ matrix.jdk == '17' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      run: ./gradlew sonarqube -PsonarToken=${{ secrets.SONAR_TOKEN }}
  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [ build ]
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        gpg-private-key: "${{ secrets.GPG_SIGNING_KEY }}"
        java-version: '11'
        cache: gradle
    - name: Deploy
      run: ./gradlew publish --no-daemon -x test -PsonatypeUsername=${{ secrets.OSSRH_USERNAME }} -PsonatypePassword=${{ secrets.OSSRH_PASSWORD }} -Psigning.keyId=${{ secrets.GPG_SIGNING_KEY_ID }} -Psigning.password=${{ secrets.GPG_PASSPHRASE }}
